<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="aditya" failures="1" tests="2" name="LoginTest" time="44.798" errors="0" timestamp="2023-12-25T20:47:57 IST">
  <testcase classname="tests.LoginTest" name="login" time="19.236">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Failed&amp;gt; but was:&amp;lt;Successfull&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Failed> but was:<Successfull>
at tests.LoginTest.login(LoginTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.LoginTest" name="login" time="16.216"/>
</testsuite> <!-- LoginTest -->
